/**
 * Regenerate data/derived from the raw sources. Output must be deterministic (no timestamps) so
 * check-drift can compare it byte for byte with the committed files.
 *
 * Phase 1 writes only the manifest of inputs; the HMRC ready-reckoner and SR25 extractions
 * arrive with the tax and spend levers.
 */
import { existsSync, readFileSync } from 'node:fs';
import path from 'node:path';
import { parseSources } from '@btc/engine';
import { readJson, sha256, writeJson } from './lib/io.js';
import { DERIVED_DIR, REPO_ROOT, SOURCES_FILE } from './lib/paths.js';

export interface DeriveOptions {
  outDir?: string;
}

export function derive(options: DeriveOptions = {}): string[] {
  const outDir = options.outDir ?? DERIVED_DIR;
  const sources = parseSources(readJson(SOURCES_FILE));
  const inputs = sources.sources
    .filter((s) => s.localPath)
    .map((s) => {
      const target = path.join(REPO_ROOT, s.localPath ?? '');
      const digest = existsSync(target) ? sha256(new Uint8Array(readFileSync(target))) : null;
      return { sourceId: s.id, localPath: s.localPath, sha256: digest };
    })
    .sort((a, b) => a.sourceId.localeCompare(b.sourceId));
  const manifest = {
    schemaVersion: 1,
    description:
      'Inputs and outputs of the derivation pipeline. Regenerated by `npm run derive`; compared in CI by `npm run check:derived`.',
    inputs,
    outputs: [] as string[],
  };
  const manifestPath = path.join(outDir, 'manifest.json');
  writeJson(manifestPath, manifest);
  return [manifestPath];
}

if (process.argv[1] && path.basename(process.argv[1]).startsWith('derive')) {
  const written = derive();
  process.stdout.write(
    `derived ${written.length} file(s):\n - ${written.map((f) => path.relative(REPO_ROOT, f)).join('\n - ')}\n`,
  );
}
