/**
 * Regenerate data/derived from the raw sources. Output must be deterministic (no timestamps) so
 * check-drift can compare it byte for byte with the committed files.
 */
import { existsSync, readFileSync } from 'node:fs';
import path from 'node:path';
import { parseSources } from '@btc/engine';
import { extractBudget2025Scorecard } from './extract-budget-2025-scorecard.js';
import { extractHmrcReadyReckoner } from './extract-hmrc-trr.js';
import { extractSr25DelTables } from './extract-sr25.js';
import { readJson, sha256, writeJson } from './lib/io.js';
import { DERIVED_DIR, REPO_ROOT, SOURCES_FILE } from './lib/paths.js';

export interface DeriveOptions {
  outDir?: string;
}

export const HMRC_EXTRACT_FILE = 'hmrc-trr-2025-06.raw.json';
export const SCORECARD_EXTRACT_FILE = 'hmt-budget-2025-table-4-1.raw.json';
export const SR25_EXTRACT_FILE = 'hmt-sr25-del.raw.json';

export async function derive(options: DeriveOptions = {}): Promise<string[]> {
  const outDir = options.outDir ?? DERIVED_DIR;
  const sources = parseSources(readJson(SOURCES_FILE));
  const inputs = sources.sources
    .filter((s) => s.localPath)
    .map((s) => {
      const target = path.join(REPO_ROOT, s.localPath ?? '');
      const digest = existsSync(target) ? sha256(new Uint8Array(readFileSync(target))) : null;
      return { sourceId: s.id, localPath: s.localPath, sha256: digest };
    })
    .sort((a, b) => a.sourceId.localeCompare(b.sourceId));

  const written: string[] = [];
  const hmrc = extractHmrcReadyReckoner();
  const hmrcPath = path.join(outDir, HMRC_EXTRACT_FILE);
  writeJson(hmrcPath, hmrc);
  written.push(hmrcPath);

  const scorecard = await extractBudget2025Scorecard();
  const scorecardPath = path.join(outDir, SCORECARD_EXTRACT_FILE);
  writeJson(scorecardPath, scorecard);
  written.push(scorecardPath);

  const sr25 = await extractSr25DelTables();
  const sr25Path = path.join(outDir, SR25_EXTRACT_FILE);
  writeJson(sr25Path, sr25);
  written.push(sr25Path);

  const manifest = {
    schemaVersion: 1,
    description:
      'Inputs and outputs of the derivation pipeline. Regenerated by `npm run derive`; compared in CI by `npm run check:derived`.',
    inputs,
    outputs: [HMRC_EXTRACT_FILE, SCORECARD_EXTRACT_FILE, SR25_EXTRACT_FILE],
  };
  const manifestPath = path.join(outDir, 'manifest.json');
  writeJson(manifestPath, manifest);
  written.push(manifestPath);
  return written;
}

if (process.argv[1] && path.basename(process.argv[1]).startsWith('derive')) {
  derive()
    .then((written) => {
      process.stdout.write(
        `derived ${written.length} file(s):\n - ${written.map((f) => path.relative(REPO_ROOT, f)).join('\n - ')}\n`,
      );
    })
    .catch((error: unknown) => {
      process.stderr.write(`${error instanceof Error ? error.message : String(error)}\n`);
      process.exit(1);
    });
}
